---
abstract: 'Punctuation-free dereferencing of arrayrefs and hashrefs'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101410, CPAN::Meta::Converter version 2.101410'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ref-List
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
version: 0.001
